In [2]:
import numpy as np

## How to create a array using numpy

In [6]:
array = np.array([[2,2,3],[5,8,7],[4,5,67]])
print(array)
print(type(array))

[[ 2  2  3]
 [ 5  8  7]
 [ 4  5 67]]
<class 'numpy.ndarray'>


## How to transpose the matrix using numpy

In [7]:
trans = np.transpose(array)
print(trans)

[[ 2  5  4]
 [ 2  8  5]
 [ 3  7 67]]


## How to flatter the matrix using the ravel function

In [9]:
flat = np.ravel(array)
print(flat)

[ 2  2  3  5  8  7  4  5 67]


## How to insert a element in a array using insert function

In [10]:
ins = np.insert(flat , 3, 600)
print(ins)

[  2   2   3 600   5   8   7   4   5  67]


In [5]:
np.random.random((5,5))

array([[0.47629241, 0.96809003, 0.10786693, 0.65537301, 0.09212366],
       [0.79968133, 0.42360187, 0.85116834, 0.3154344 , 0.4000534 ],
       [0.67496696, 0.84639354, 0.54233826, 0.60058888, 0.40037327],
       [0.11318592, 0.87854557, 0.17567238, 0.38298108, 0.31935782],
       [0.1239372 , 0.49842298, 0.87551183, 0.60744466, 0.433006  ]])